language: php

php:
    - 5.6
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer self-update && composer install --dev
    - vendor/tedivm/dovecottesting/SetupEnvironment.sh

script: ./tests/runTests.sh

after_script:
    - php vendor/bin/coveralls -v

matrix:
    fast_finish: true